// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYs0hJgjZAX5XXG6EXzcukyS3nNnsmBhY',
    appId: '1:673823833725:web:55dccd63dfce6466a3fb14',
    messagingSenderId: '673823833725',
    projectId: 'income-expense-tracker-d79ac',
    authDomain: 'income-expense-tracker-d79ac.firebaseapp.com',
    storageBucket: 'income-expense-tracker-d79ac.firebasestorage.app',
    measurementId: 'G-ZX3HTMB2FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jG2z9RpMMLcNCwDB_qCy_CWXFdB6GMM',
    appId: '1:673823833725:android:cbaa9fec0893777ea3fb14',
    messagingSenderId: '673823833725',
    projectId: 'income-expense-tracker-d79ac',
    storageBucket: 'income-expense-tracker-d79ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQcLvYjBb_UDoxbO43npR96bClw7_TR0',
    appId: '1:673823833725:ios:d432531f3a966617a3fb14',
    messagingSenderId: '673823833725',
    projectId: 'income-expense-tracker-d79ac',
    storageBucket: 'income-expense-tracker-d79ac.firebasestorage.app',
    iosBundleId: 'com.example.incomeExpenseTracker',
  );
}
